export const INPUT_SEARCH = "INPUT_SEARCH";

export const ADD_CART_ITEM="ADD_CART_ITEM";

export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";

export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";

